version: '3'
services:
  web:
    build:
      context: ./web-container
      dockerfile: web-container-dockerfile
    volumes:
      - ./web-container/htdocs:/usr/share/nginx/html
    expose:
      - "80"
    ports:
      - "9005:80"
  db:
    build:
      context: ./db-container
      dockerfile: db-container-dockerfile
    volumes:
      - ./db-container/db_init_scripts/fill_data.sql:/docker-entrypoint-initdb.d/fill_data.sql
    env_file: ./db-container/db.env
    expose:
      - "3306"
    ports: 
      - "3306:3306"


